#' Prime Factors
#'
#' Get prime factors of given number using a list of prime numbers.
#' @param number A number to be factorized.
#' @param primes Optional. A vector of prime numbers to be used in the factorization. This makes the process faster, avoiding having to generate the first primes one by one. If not given, an initial vector of primes below 100 will be used as first input; the rest of primes will be generated by this algorithnm as needed.
#' @return Vector of primes factors.
#' @keywords primes
#' @export
#' @examples
#' primes <- get_primes(100)
#' prime_factors(primes, 100)

prime_factors <- function(number, primes) {
    if(number <= 1)
        return(NA)

    # If no vector of primes given, get all primes below 100 to begin with.
    p <- get_primes(100)
    if (missing(primes))
        primes <- p

    p_factors <- vector() # vector of prime factors
    i <- 0

    while (number > 1) {
        i <- i + 1

        # Failsafe: if prime factors > max(primes),
        # then get next prime through the following...
        if (i > length(primes)) {
            next_n <- primes[i-1] + 2

            while (TRUE) {
                count <- 0

                for (j in primes) {
                    if(next_n%%j == 0) { # break if divisible by any previous prime
                        break()
                    } else {
                        count <- count + 1
                    }
                }

                if (count == length(primes)) {
                    primes[i] <- next_n
                    break()
                }

                next_n <- next_n + 2
            }
        }

        n <- primes[i]

        while (number %% n == 0) {
            p_factors[length(p_factors)+1] <- n
            number <- number/n
        }
    }

    return(p_factors)
}
